// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type DailyGoal struct {
	ID          int64         `json:"id"`
	Discription string        `json:"discription"`
	Completed   bool          `json:"completed"`
	UserID      sql.NullInt32 `json:"user_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

type MonthlyGoal struct {
	ID          int64         `json:"id"`
	Discription string        `json:"discription"`
	Completed   bool          `json:"completed"`
	UserID      sql.NullInt32 `json:"user_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
}

type WeeklyGoal struct {
	ID          int64         `json:"id"`
	Discription string        `json:"discription"`
	Completed   bool          `json:"completed"`
	UserID      sql.NullInt32 `json:"user_id"`
	CreatedAt   time.Time     `json:"created_at"`
}
