// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMovie(ctx context.Context, id int64) error
	DeleteRating(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetMovie(ctx context.Context, id int64) (Movie, error)
	GetMovieRatings(ctx context.Context, movieID sql.NullInt32) ([]Rating, error)
	GetMovies(ctx context.Context, arg GetMoviesParams) ([]Movie, error)
	GetRating(ctx context.Context, id int64) (Rating, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserRatings(ctx context.Context, userID sql.NullInt32) ([]Rating, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error)
}

var _ Querier = (*Queries)(nil)
